# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: t.o.brier@bham.ac.uk
author_name: Thomas Brier
create_claude_symlink: true
create_gemini_symlink: true
has_ai_rules: true
has_binder: true
has_settings: true
kind: frontend-and-server
labextension_name: climb-jupyter-base
project_short_description: Base functionality for CLIMB JupyterLab Extensions.
python_name: climb_jupyter_base
repository: https://github.com/CLIMB-TRE/climb-jupyter-base
test: true

